title: 山屿智能文档中心
description: 产品文档库
baseurl: ""
url: "https://shanyuknowledge.github.io"
github_username: ShanyuKnowledge
github_repository: ShanyuKnowledge.github.io
permalink: /:title/

theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
  - jekyll-feed

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  docs:
    output: true
    permalink: /docs/:path/